### ISSUE TITLE
ldmadmin newlog does not rotate log files when LDM is used as a NOAAport ingester

### ISSUE THREAD

**Issue by sebenste** [Unidata/LDM#116]
Hello Stonie and Steve,

If I have a NOAAport ingest server running the LDM, it is recommended that I use nwstg.log, nwstg2.log, etc...a different log file for each of the product ID's. The problem is that when this is done, using "ldmadmin newlog" in crontab only the ldmd.log file gets rotated, not the other ones. The LDM should know that the log files are active and should be rotated. This caused a problem on one of our NOAAport servers where the log wasn't rotated for 3 years since install.

Thanks!

Gilbert

**Comment by semmerson** [comment]
Yeah. We haven't gotten around to rotating the idiosyncratic log files in the LDM configuration-file: only the standard LDM log file is rotated by "ldmadmin newlog".

You can use the newlog(1) script in crontab(1) entries to rotate these files. If you do, don't forget to invoke refresh_logging(1) at the end.
