### ISSUE TITLE
LDM losing products in queue on start

### ISSUE THREAD

**Issue by dopplershift** [Unidata/LDM#44]
As noticed from our AWS NEXRAD level 2 machine, when the LDM starts, it compares the wall clock against the product *creation* time, rather than the product *insertion* time. This causes us to lose a few NEXRAD chunks when restarting the LDM.

**Comment by dopplershift** [comment]
This is fixed for me in the 6.12.15.28 build, so I'm guessing this can be closed.

**Comment by semmerson** [comment]
Fixed. Will be in the next release.
