### ISSUE TITLE
LDM configure should check for presence of `dc`, needed for scour to work

### ISSUE THREAD

**Issue by akrherz** [Unidata/LDM#55]
Perhaps the `scour` utility is not considered intrinsic to the installation of LDM, but it would be nice if `configure` reported an error when the `dc` program is not found in the current $PATH.  On a base install of RHEL7, the `bc` RPM is not installed :(

**Comment by semmerson** [comment]
The `scour(1)` utility is a supported one in the LDM package.

Operating systems that claim X/Open compliance are required to have the `bc(1)` utility. I'm saddened (but not all that surprised) that RHEL-7 doesn't.

A fix will be in the next release (after 6.13.5). In the meantime, you can replace these lines in the file `$LDMHOME/src/scour/scour.in`:

    sed 's/\([0-9]*\) \([0-9]*\).*/b=\1;a=\2;d=0;if(a<b)d=b-a;d/'|\
     bc`

with this line:

    awk '{diff=$1-$2; print (diff < 0) ? 0 : diff;}'`

Then, execute the command `make install` in the directory that contains the file to install the modified `scour(1)` script.

Thanks for sending this in.
