### ISSUE TITLE
Ingest of badly corrupted GRIB data can crash NOAAportIngester

### ISSUE THREAD

**Issue by sebenste** [Unidata/LDM#71]
As of this day when the issue is being reported, all operational versions of the LDM, up to and including beta version 6.13.12.24, has a bug whereby a badly corrupted GRIB file can cause the NOAAport ingester to crash. That, in turn, causes the rest of the LDM to terminate as well. On 9/25/2019, this bug caused the LDM at every National Weather Service forecast office in the United States to crash after a badly corrupted grib file was uplinked to NOAAport.

It also crashed the LDM at multiple universities as well that receive NOAAport, including the popular College of DuPage website.

**Comment by sebenste** [comment]
WORKAROUND: Run a script in crontab that checks to see if the LDM is running every minute. If it is not, you can restart the LDM. Unfortunately, this does mean that up to 60 seconds of data could be lost, but it's a lot better than the LDM staying down.

**Comment by semmerson** [comment]
Because the legacy NOAAPort ingestion code for GRIB2 messages is a big ball of mud, a work-around script that restarts a crashed ingester has been created. The script is called `keep_running` and will be in the next release.

Here's the script if you want to use it now:

    # Script to start a program and restart it whenever it terminates.

    while true; do
        "$@"
        status=$?
        ulogger -p error "Process '$@' terminated with status $status. Restarting"

        # Edit/uncomment the following command to receive an email notification
        # mailx -s "Process '$@' terminated with status $status. Restarting" \
        #       $LOGNAME </dev/null
    done`

Simply add the script to the LDM user's `bin/` subdirectory.

Here's an example of using it in the LDM configuration-file:

    exec    "keep_running noaaportIngester -n -m 224.0.1.1  -l /data/tmp/nwstg.log"

**Comment by sebenste** [comment]
Due to the bug fix in the upcoming LDM 6.13.12, this can be closed.
