### ISSUE TITLE
Create registry parameter for average product size

### ISSUE THREAD

**Issue by semmerson** [Unidata/LDM#72]
This value would be used when the number of slots parameter is set to "default".

**Comment by mustbei** [comment]
To clarify:
- when the slots parameter is "default", use this new average_product_size as the replacing slots parameter value, like so:
        slots = average_product_size  ?  (<-- my understanding)
- Or, rather, use it to compute it, like so:
       slots = average_product_size / 56K ?

**Comment by mustbei** [comment]
Completed in new ldmadmin.

**Comment by semmerson** [comment]
The default number of slots is (size_of_queue_in_bytes /
average_product_size_in_bytes)

The average product size is in the 50K byte range.
