### ISSUE TITLE
Have "ldmadmin mkqueue -f" check the available size

### ISSUE THREAD

**Issue by semmerson** [Unidata/LDM#79]
If the user specifies the "-f" (fast) option, then ldmadmin(1) could use df(1) to obtain the amount of available space for the queue and compare that against the queue-size parameter in the registry and error-exit if there's insufficient space. This would prevent the product-queue module from receiving a SIGBUS when trying to stuff two cubic feet into a one cubic foot box.

**Comment by mustbei** [comment]
Implemented within new Python-based ldmadmin.

**Comment by semmerson** [comment]
Excellent.

Go ahead and close this issue.

Regards,
Steve Emmerson
