### ISSUE TITLE
pqact option of -gunzip 

### ISSUE THREAD

**Issue by sebenste** [Unidata/LDM#99]
More and more, to save bandwidth, the NWS is sending files across their fiber or NOAAport feeds gzipped.
I would like an -gunzip and an -unzip option in pqact to automatically unzip the file before writing to disk or running an action on the server. This would save a big extra step in post-processing of these files.

**Comment by NaderCHASER** [comment]
An "-unzip" flag that covers both GZipped and Zipped files would be nice to have.

I _think_ that Unidata's MRMS feed comes in GZipped and is re-inserted decompressed so this might even help with that use case.

**Comment by semmerson** [comment]
This can be done by piping the data-product (using the "-close" option) to a script that decompresses its standard input on the fly into a file and then uses the AWIPS script "/awips2/ldm/dev called notifyAWIPS2-unidata.py" to notify Qpid about the file.
